name: Build and Publish
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Executables
          path: target/release/bpc
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/bpc
          tag_name: v0.2.0
          name: v0.2.0
